### ISSUE TITLE
Problem with datepicker in popup

### ISSUE THREAD

**Issue by Cedperso** [dcapslock/hass-browser_mod#20]
My Home Assistant version: 2025.3.4

Hi,

I noticed a problem with the datepicker of an 'input_datetime' entity.

If you insert an entity in the dashboard in the usual way, like this:

`type: entities
entities:

    entity: input_datetime.mydatepicker`

When you click on the date field, a datepicker pops up.

If I insert the "input_datetime" in a browsermod popup window like this:
```
cards:

type: custom:mushroom-template-card
name: Programmation
primary: Programmation
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      title: Programmer la date
      content:
        type: entities
        entities:
          - entity: input_datetime.mydatepicker
            name: Date
```

Here, when you click on the date field, the datepicker open in rear of the browsermod popup, but not usable. The popup of browser mode leave in front of all.

Do you have any ideas on how to resolve this issue?

Thank you very much.
