### ISSUE TITLE
FR: Default view for browser/user

### ISSUE THREAD

**Issue by tbrasser** [dcapslock/hass-browser_mod#27]
We already have default dashboard setting, however I have a single dashboard that I use for phone/(wall)tablet/desktop.

I solve this now via FKB/starturl, but it would be great to have it more integrated into HA (via browser_mod).

I understand this might be difficult to implement, would also be interrested in alternatives. Maybe I just need to create more dashboards with different 'first' views (and re-use the yaml) but this might have a performance impact?

**Comment by dcapslock** [comment]
@tbrasser I am not sure how easy this will be to do. The simplicity of the current feature is that it just a browser mod wrapper around setting a Dashboard, the same as a user can do via user settings. This in the end just uses `localStorage['defaultPanel']`. I have tried playing with that, but can't get to work with views. 

I have had a quick test and it would appear that if dashboard home view is not visible to a user, then it will pick the next as default view. So you could possible solve with visibility per user.

**Comment by dcapslock** [comment]
@tbrasser another method is using an automation detecting when a browser navigates to a particular dashboard home, set that browser to your desired view. I have included a test sample automation below (notifcation and delay for visual test purposes only). You can extend to include multiple browsers path sensors as triggers, including their browserID and desired paths in `toPathLookup`, using lowercase browserID as key (or adjust template to your desire).

```yaml
alias: Test Dashboard Navigate
description: ""
triggers:
  - trigger: state
    entity_id:
      - sensor.ios_virtual_browser_path
    to: null
conditions:
  - condition: template
    value_template: "{{ trigger.to_state.state == '/dashboard-test/0' }}"
actions:
  - variables:
      to_path: |
        {% set toPathLookup = { 
                'ios-virtual': '/dashboard-test/test-view-2'
          } 
        %}
        {{ toPathLookup[trigger.to_state.attributes.browserID | lower] }}
  - action: browser_mod.notification
    metadata: {}
    data:
      browser_id:
        - "{{ trigger.to_state.attributes.browserID }}"
      message: Navigating to {{ to_path }}
  - delay:
      hours: 0
      minutes: 0
      seconds: 4
      milliseconds: 0
  - action: browser_mod.navigate
    metadata: {}
    data:
      browser_id:
        - "{{ trigger.to_state.attributes.browserID }}"
      path: "{{ to_path }}"
mode: single
```
