### ISSUE TITLE
Popup Card actions not working

### ISSUE THREAD

**Issue by dcapslock** [dcapslock/hass-browser_mod#31]
My Home Assistant version: 2025.4.2

**What I am doing:**

Using Popup Card with Right/Left Button actions.

**What I expected to happen:**

Actions to perform

**What happened instead:**

Action does not perform. In console the following is logged.

**Minimal** steps to reproduce:

Popup Card below. Found that the issue is with yaml config after the actions. Somehow this overwrites actions.

```yaml
type: custom:popup-card
entity: sensor.sun_next_dawn
title: Custom popup
size: classic
card:
  type: vertical-stack
  cards:
    - type: vertical-stack
      cards:
        - type: history-graph
          entities:
            - sun.sun
        - type: entity
          entity: sun.sun
        - type: entity
          entity: sensor.sun_next_dawn
        - type: button
          name: Test Large More Info
          tap_action:
            action: perform-action
            perform_action: browser_mod.more_info
            target: {}
            data:
              large: true
              entity: sun.sun
timeout_hide_progress: false
style: |-
  ha-dialog {
     background: blue;
  }
right_button: Toggle Light
right_button_action:
  service: light.toggle
  target:
    entity_id: light.bed_light
left_button: Toggle Light
left_button_action:
  service: light.toggle
  target:
    entity_id: light.bed_light
allow_nested_more_info: true
dismissable: true
```

**Error messages from the browser console:**

```
Browser Mod: Service parameter not specified in service call.
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
- [X] If this issue is to do with an Android device losing connection, sensors becoming unavailable etc., please confirm you have read, understood and tried methods described in Wiki Article [Andoird Devices 'Always On'](https://github.com/dcapslock/hass-browser_mod/wiki/Andoird-Devices-'Always-On')
