### ISSUE TITLE
card-mod behaviour with themes irregular

### ISSUE THREAD

**Issue by dcapslock** [dcapslock/hass-browser_mod#35]
My Home Assistant version: 2025.4.2

**What I am doing:**

Using card-mod theme variables to apply Popup styling.

**What I expected to happen:**

Sty;ing is always applied correctly.

**What happened instead:**

Styling gets applied late or not at all.

**Minimal** steps to reproduce:

Theme yaml
```yaml
...
  card-mod-theme: my-theme
  card-mod-more-info-yaml: |
    ha-dialog$: |
      div.mdc-dialog__surface {
        background: teal !important;
      }
```

I have found that if I use `card_mod:` section in the popup, referencing the selector, then everything works 100%.

```
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      title: "My title "
      card_mod:
        style:
          ha-dialog$: null <-- important for workaround!!
```

**Error messages from the browser console:**

NA

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
      
- [X] If this issue is to do with an Android device losing connection, sensors becoming unavailable etc., please confirm you have read, understood and tried methods described in Wiki Article [Andoird Devices 'Always On'](https://github.com/dcapslock/hass-browser_mod/wiki/Andoird-Devices-'Always-On')

**Comment by dcapslock** [comment]
Note, styling for the main `ha-dialog` element seems to work OK. It is only items in Shadow DOM that have the issue.

**Comment by dcapslock** [comment]
More on workaround. It is as simple as having a valid style (non empty string). If not then card-mod will not merge theme as its compare_deep function returns true for one of the inputs being empty!

So for my example, this will work. The fix for browser mod will be to pass such an empty style to force the theme styles to be merged.

```yaml
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      title: "My title "
      card_mod:
        style: |
          {}
```
